stages:
  - build
  - deploy

# -------------------------
# DEPLOY SUR VPS
# -------------------------
deploy:
  stage: deploy
  image: alpine:latest
  tags:
    - vps-docker
  script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - ssh -o StrictHostKeyChecking=yes "$SSH_USER@$SSH_HOST" "cd /home/deploy/portfolio && docker compose pull && docker compose up -d --remove-orphans"
  only:
    - main
