stages:
  - build
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

# -------------------------
# BUILD DOCKER IMAGE
# -------------------------
build:
  stage: build
  image: docker:24
  services:
    - docker:dind
  tags:
    - vps-portfolio
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

# -------------------------
# DEPLOY SUR VPS
# -------------------------
deploy:
  stage: deploy
  tags:
    - vps-portfolio
  script:
    - echo "Deploying..."
    - ssh root@YOUR_VPS_IP "
      cd /home/deploy/portfolio &&
      docker compose pull &&
      docker compose up -d
      "
